template: |
  ### What's Changed

  $CHANGES

  See full comparison at [$PREVIOUS_TAG...master](https://github.com/denysdovhan/spaceship-prompt/compare/$PREVIOUS_TAG...master)

change-template:
  $TITLE - @AUTHOR


