language: node_js
node_js:
  stable
install: true

jobs:
  include:
    - stage: deploy gitbook
      if: branch = master AND type = push
      script:
        - npm install --only=dev --ignore-scripts
        - npm run docs:build
      deploy:
       provider: pages
       skip-cleanup: true
       github-token: $GITHUB_TOKEN
       keep-history: true
       local-dir: _book

